#
# Create release on GitHub when release branch is pushed
#
name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-tag: ${{ steps.autotag.outputs.new-tag }}
      release-url: ${{ steps.release.outputs.html_url }}
    steps:
      - name: Increment version tag
        id: autotag
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true

      - name: Create pre-release
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          makeLatest: false
          prerelease: true
          skipIfReleaseExists: true
          tag: v${{ steps.autotag.outputs.new-tag }}