#
# Create release on GitHub when release branch is pushed
#
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: generate_notes
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const { execSync } = require('child_process');
            const tag = context.ref.replace('refs/tags/', '');
            const previousTag = execSync('git describe --tags --abbrev=0 ' + tag + '^').toString().trim();
            const changes = execSync(`git log ${previousTag}..${tag} --pretty=format:'- %s'`).toString().trim();
            return changes;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.generate_notes.outputs.result }}
          draft: false
          prerelease: false